ZelloVoice/ZelloVoice.Web/Areas/HelpPage/Controllers/HelpController.cs
using System;
using System.Web.Http;
using System.Web.Mvc;
using ZelloVoice.Web.Areas.HelpPage.ModelDescriptions;
using ZelloVoice.Web.Areas.HelpPage.Models;

namespace ZelloVoice.Web.Areas.HelpPage.Controllers
{
    /// <summary>
    /// The controller that will handle requests for the help page.
    /// </summary>
    public class HelpController : Controller
    {
        private const string ErrorViewName = "Error";

        public HelpController()
            : this(GlobalConfiguration.Configuration)
        {
        }

        public HelpController(HttpConfiguration config)
        {
            Configuration = config;
        }

        public HttpConfiguration Configuration { get; private set; }

        public ActionResult Index()
        {
            ViewBag.DocumentationProvider = Configuration.Services.GetDocumentationProvider();
            return View(Configuration.Services.GetApiExplorer().ApiDescriptions);
        }

        public ActionResult Api(string apiId)
        {
            if (!String.IsNullOrEmpty(apiId))
            {
                HelpPageApiModel apiModel = Configuration.GetHelpPageApiModel(apiId);
                if (apiModel != null)
                {
                    return View(apiModel);
                }
            }

            return View(ErrorViewName);
        }

        public ActionResult ResourceModel(string modelName)
        {
            if (!String.IsNullOrEmpty(modelName))
            {
                ModelDescriptionGenerator modelDescriptionGenerator = Configuration.GetModelDescriptionGenerator();
                ModelDescription modelDescription;
                if (modelDescriptionGenerator.GeneratedModels.TryGetValue(modelName, out modelDescription))
                {
                    return View(modelDescription);
                }
            }

            return View(ErrorViewName);
        }
    }
}

ZelloVoice/ZelloVoice.Web/Controllers/ZelloController.cs
using PttLib;
using AxPttLib;

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;
using ZelloVoiceWeb.Controllers;

using Trimble.MobileSolutions.Business.Entities.Assets;
using Trimble.MobileSolutions.Business.Entities.Events;
using Trimble.MobileSolutions.Business.Entities.Security;
using Trimble.MobileSolutions.Data.Mappers.Assets;
using Trimble.MobileSolutions.Data.Mappers.Security;
using BusinessAssets = Trimble.MobileSolutions.Business.Entities.Assets;
using Trimble.MobileSolutions.Business.Entities.Events.RealTime.AssetInfo;
//using Trimble.MobileSolutions.Map.Objects;
//using Trimble.MobileSolutions.Map.ConnectedFleet.ALKMaps.JsModel;
using Newtonsoft.Json;


namespace ZelloVoice.Web.Controllers
{

    
    

    [AllowAnonymous]
    public class ZelloController : Controller
    {



       // AssetService.AssetWS AssetWS = new AssetService.AssetWS();
       
         // GET: Zello
         [AllowAnonymous]
        public ActionResult Index()
        {          

            try
            {

                //ISecurity mapper = Trimble.MobileSolutions.Data.Mappers.Factory.GetMapper<ISession, ISecurity>();
                //ISession session = null;
                //session = mapper.GetSession("QA FT", "tester22", "test");
                //result = AssetWS.GetAssets(Test)


            }
            catch (Exception ex)
            {

               
              
            }
            
            return View();
        }

       
    }
}

ZelloVoice/ZelloVoice.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        @if (User.Identity.IsAuthenticated)
            {
            <div class="container">

                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <a href='@Url.Action("Index", "Home", new { area = "" }, null)'>
                        <img src="~/Images/ZelloLogo.png" style="padding-top: 10px;" height="40px" width="100px" />
                    </a>

                    @*@Html.ActionLink("Zello Voice", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, null)</li>
                        @*<li>@Html.ActionLink("API", "Index", "Help", new { area = "HelpPage" }, null)</li>*@
                        <li>@Html.ActionLink("Zello voice", "Index", "Zello", new { area = "" }, null)</li>
                    </ul>
                    @Html.Partial("_LoginPartial")
                </div>
            </div>
        }
    </div>
    <div class="container body-content">
        @RenderBody()
        @RenderSection("SPAViews", required: false)
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Trimble</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("Scripts", required: false)
</body>
</html>